name: Deploy to Hostinger Using GitHub Actions

on:
  push:
    branches:
      - main # The branch name your are commiting the new changes
jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

