name: workflow test

on:
  push:
    branches:
      - main

jobs:
  build:
    name: my first job
    runs-on: ubuntu-latest
    steps:
      - name: my first step
        uses: actions/checkout@v4

      - name: Greetings
        run: echo "Hello to DevOps !"
