name: Deploy to Hostinger

on:
  push:
    branches:
      - main # The branch name your are commit the new changes
jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - run: echo "Host > $myhost"
        env:
          myhost: ${{ secrets.HOST }}
