name: Deploy to Hostinger

on:
  push:
    branches:
      - main # The branch name your are commit the new changes
jobs:
  build_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd domains && ls -l && chmod 777 wassimkaouia.online && ls -l && cd wassimkaouia.online/public_html && ls -l && rm -rf * && git clone https://github.com/wassim-kaouia/my-devops-portfolio.git .'
